const HC_FILES = [
    { file: 'CASOS/hc_abdomen_agudo.html', title: 'Abdómen Agudo', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_acv.html', title: 'ACV', category: 'cardiologia', icon: '❤️', time: '30 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_apendicitis.html', title: 'Apendicitis', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_asma.html', title: 'Asma', category: 'medicina', icon: '🩺', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_cesarea.html', title: 'Cesárea', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_chagas.html', title: 'Chagas', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_chikungunya.html', title: 'Chikungunya', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_crecimiento_y_desarrollo.html', title: 'Crecimiento y Desarrollo', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_dengue.html', title: 'Dengue', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_diabetes_m.html', title: 'Diabetes M.', category: 'medicina', icon: '🩺', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_edas_y_dsht.html', title: 'EDAS y DSHT', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_enfermedades_de_vias_biliares.html', title: 'Enfermedades de Vías Biliares', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_epoc.html', title: 'EPOC', category: 'medicina', icon: '🩺', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_exantematicas_torch.html', title: 'Exantemáticas / TORCH', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_fiebre_reumatica.html', title: 'Fiebre Reumática', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_hemorragias_de_la_1a_mitad_del_embarazo.html', title: 'Hemorragias de la 1ª mitad del embarazo', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_hemorragias_de_la_2a_mitad_del_embarazo.html', title: 'Hemorragias de la 2ª mitad del embarazo', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_hemorragias_digestivas.html', title: 'Hemorragias Digestivas', category: 'medicina', icon: '🩺', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_hernias.html', title: 'Hérnias', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_hta.html', title: 'HTA', category: 'cardiologia', icon: '❤️', time: '30 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_icc.html', title: 'ICC', category: 'cardiologia', icon: '❤️', time: '30 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_ictericia_neonatal.html', title: 'Ictericia Neonatal', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_introduccion_a_gob.html', title: 'Introducción a GOB', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_ira_irc_sdr_nefritica_y_nefrotica.html', title: 'IRA, IRC, SDR Nefrítica y Nefrótica', category: 'cardiologia', icon: '❤️', time: '30 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_iras.html', title: 'IRAs', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_itu.html', title: 'ITU', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_lactancia_materna.html', title: 'Lactancia Materna', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_malaria.html', title: 'Malaria', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_neumonia.html', title: 'Neumonía', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_obstruccion_intestinal.html', title: 'Obstrucción Intestinal', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_pai.html', title: 'PAI', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_pancreatitis.html', title: 'Pancreatitis', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_parto.html', title: 'Parto', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_planificacion_familiar.html', title: 'Planificación Familiar', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_puerperio.html', title: 'Puerperio', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_quemaduras.html', title: 'Quemaduras', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_rabia.html', title: 'Rabia', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_reanimacion_neonatal.html', title: 'Reanimación Neonatal', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_recepcion_neonatal.html', title: 'Recepción Neonatal', category: 'pediatria', icon: '👶', time: '25 min', difficulty: 'medio' },
    { file: 'CASOS/hc_sepsis_itu.html', title: 'Sepsis / ITU', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_shock_fraturas.html', title: 'Shock Fraturas', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_sindrome_coronaria_iam.html', title: 'Síndrome Coronaria (IAM)', category: 'cardiologia', icon: '❤️', time: '30 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_the.html', title: 'THE', category: 'obstetricia', icon: '👩‍⚕️', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_topografia_abdominal.html', title: 'Topografía Abdominal', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_trauma.html', title: 'Trauma', category: 'cirurgia', icon: '🔪', time: '35 min', difficulty: 'dificil' },
    { file: 'CASOS/hc_tuberculosis.html', title: 'Tuberculosis', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_vih.html', title: 'VIH', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
    { file: 'CASOS/hc_zika.html', title: 'Zika', category: 'infecciosa', icon: '🦠', time: '30 min', difficulty: 'medio' },
];
